name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
#   only triggers on ip-whitelist subdirectory
    paths:
      - 'seft-ci-ingestion/main.py'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'seft-ci-ingestion/main.py'
      - '.github/workflows/test.yml'


jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Basic test order 1"
